baseurl = "https://cnpmornantais.fr"
title = "Cercle des Nageurs du Pays Mornantais"
languageCode = "fr"
theme = "cnpm"
canonifyurls = true
paginate = 10
copyright = "Code released under the Apache 2.0 license."

[author]
    name = "cnpm"

[params]
  shortTitle = "CNPM"
  DateForm = "Mon, 2 Jan, 2006"
  Description = "Cercle des nageurs du pays mornantais"
  Author = "cnpm"
  email = "contact@cnpmornantais.fr"
  Ganalytics = "UA-87654846-1"
  Keywords = "natation,mornant,ffn,cnpm"

[[params.social]]
  title = "github"
  url = "https://github.com/yoyey/cnpmornantais"
