baseurl = "https://cnpmornantais.fr"
title = "Cercle des Nageurs du Pays Mornantais"
languageCode = "fr-fr"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "fr"
theme = ["cnpm"]
canonifyurls = true
paginate = 10
copyright = "Code released under the Apache 2.0 license."
googleAnalytics = "UA-87654846-1"

[markup.goldmark.renderer]
  unsafe= true

[menu]

# Main menu

[[menu.main]]
    name = "Saison 2020-2021"
    url  = "/agenda/"
    weight = 1

[[menu.main]]
    name = "L'association"
    url  = "/association/"
    weight = 2

[[menu.main]]
    name = "Natation sportive"
    url  = "/natation/"
    weight = 3

[[menu.main]]
    name = "Natation synchronis√©e"
    url  = "/synchro/"
    weight = 4

[[menu.main]]
    name = "BNSSA"
    url  = "/bnssa/"
    weight = 5

[[menu.main]]
    name = "Tarifs et inscription"
    url  = "/tarifs/"
    weight = 6

[[menu.main]]
    name = "Contact"
    url  = "/contact/"
    identifier = "contact"
    weight = 7


[author]
    name = "cnpm"

[params]
  shortTitle = "CNPM"
  DateForm = "Mon, 2 Jan, 2006"
  Description = "Cercle des nageurs du pays mornantais"
  Author = "cnpm"
  email = "contact@cnpmornantais.fr"
  Keywords = "natation,mornant,ffn,cnpm,synchro,natation artistique"

[[params.social]]
  title = "github"
  url = "https://github.com/yoyey/cnpmornantais"
[[params.social]]
    title = "facebook"
    url = "https://www.facebook.com/Synchro-CNPM-102581368152227/"
[[params.social]]
    title = "instagram"
    url = "https://instagram.com/synchrocnpm?igshid=q4zr6t44oxmx"
